name: CI

on:
  push:
    branches:
      - main  # ou la branche de votre choix

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: ğŸ“¥ Checkout project
      uses: actions/checkout@v2

    - name: ğŸ“¦ Install dependencies
      run: npm install

    - name: ğŸ—ƒï¸ Generate Prisma schema
      run: npx prisma generate

    - name: ğŸ”¨ Build .env from GitHub secrets
      run: |
        echo "DATABASE_URL='${{ secrets.DATABASE_URL }}'" >> .env
        echo "MONGODB_URL='${{ secrets.MONGODB_URL }}'" >> .env
    - name: Oui
      run: ls -la

    - name: ğŸ§ª Execute tests
      run: npm run test
